/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LeerTeclasUsandoC */

#ifndef _Included_LeerTeclasUsandoC
#define _Included_LeerTeclasUsandoC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LeerTeclasUsandoC
 * Method:    leerTecla
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_LeerTeclasUsandoC_leerTecla
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
