/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LeerTeclasUsandoCPP */

#ifndef _Included_LeerTeclasUsandoCPP
#define _Included_LeerTeclasUsandoCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LeerTeclasUsandoCPP
 * Method:    leerTecla
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_LeerTeclasUsandoCPP_leerTecla
  (JNIEnv *, jobject);

/*
 * Class:     LeerTeclasUsandoCPP
 * Method:    hayTeclaPulsada
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_LeerTeclasUsandoCPP_hayTeclaPulsada
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
